[background]
# gif, png, jpg
type                    = "jpg"

[bar]
vertical_padding        = 1.5
background-color        = "#2a2462"
chord                   = "#927acc"
text                    = "#5e50b0"

[border]
focused                 = "#000000"
unfocused               = "#000000"
width                   = 0
gap                     = 20
round                   = 20

[fonts]
family                  = "Cantarell"
size                    = 24

[tags]
# border, block, text, line
highlight_method        = "block"
urgent_method           = "block"

width                   = 0
active                  = "#927acc"
inactive                = "#5e50b0"
current_color           = "#d6a7b5"
urgent                  = "#ffffff"
current_font_color      = "#423a85"
urgent_font_color       = "#423a85"
