[background]
# gif, png, jpg
type                    = "jpg"

[bar]
vertical_padding        = 1.5
background-color        = "#edebf2"
chord                   = "#694559"
text                    = "#271b24"

[border]
focused                 = "#000000"
unfocused               = "#000000"
width                   = 0
gap                     = 20
round                   = 20

[fonts]
family                  = "Fira Code"
size                    = 24

[tags]
# border, block, text, line
highlight_method        = "block"
urgent_method           = "block"

width                   = 0
active                  = "#271b24"
inactive                = "#694559"
current_color           = "#8462d7"
urgent                  = "#8462d7"
current_font_color      = "#edebf2"
urgent_font_color       = "#edebf2"
